In [ ]:
#Control Statments
#control the flow of execution in a program
#allows you to make decisions, repeat actions, or exit loops based on specific conditions


In [ ]:
#if Statement: Executes a block if the condition is True.
#if-else Statement: Executes one block if the condition is True, otherwise executes another block.
#if-elif-else Statement: Allows multiple conditions to be checked sequentially.

In [ ]:
#if Statement:

In [2]:
a = 7
if a > 5:
    print("a value is correct")

a value is correct


In [5]:
a = 1
if a > 5:
    print("a value is correct")
else:
    print("a value is less")

a value is less


In [10]:
a = 5
if a > 5:
    print("a value is correct")
elif a==5:
    print("a value is equal")
else:
    print("a value is less")
    

a value is equal


In [ ]:
# Looping Statements

In [ ]:
#These are used to repeat a block of code multiple times.
#for Loop: Iterates over a sequence (like a list, tuple, or string).
#while Loop: Repeats as long as a condition is True.

In [11]:
#For loop example
for i in range(3):
    print(f"Iteration {i}")

Iteration 0
Iteration 1
Iteration 2


In [12]:
# While loop example
count = 0
while count < 3:
    print(f"Count is {count}")
    count += 1

Count is 0
Count is 1
Count is 2


In [ ]:
#These are used to alter the normal flow of loops.
#break: Exits the loop prematurely.
#continue: Skips the current iteration and moves to the next one.
#pass: Does nothing; used as a placeholder.

In [14]:
# Break example
for i in range(2,10):
    if i == 7:
        break
    print(i)


2
3
4
5
6


In [16]:
# Continue example
for i in range(1,12):
    if i == 7:
        continue
    print(i)


1
2
3
4
5
6
8
9
10
11


In [18]:
# Pass example
for i in range(6):
    if i == 3:
        pass  # Placeholder for future code
    print(i)

0
1
2
3
4
5


In [ ]:
#File Handling :  files—reading, writing, and manipulating them
#Opening a File:
#Reading a File:
#Writing to a File:


In [ ]:
#Opening a File:
file = open("hello.txt", "r") 

In [ ]:
#Reading a File:
with open("example.txt", "r") as file:
    content = file.read()  # Reads the entire file
    print(content)

In [ ]:
#Writing to a File:
with open("example.txt", "w") as file:
    file.write("Hello, World!")  # Overwrites the file

In [ ]:
#appending file
with open("example.txt", "a") as file:
    file.write("\nAppending this line.")

In [ ]:
#Closing a File
file.close()

In [ ]:
#read methods
read(): #Reads the entire file.
readline(): #Reads one line at a time.
readlines(): #Returns a list of all lines.

In [ ]:
#write methods
write(): # Writes a string to the file.
writelines(): # Writes a list of strings.

In [ ]:
#Exception Handling
#handle runtime errors , ensuring the program doesn't crash unexpectedly

In [ ]:
#Components
#try Block: Code that might raise an exception is placed here.
#except Block: Handles the exception if it occurs.
#else Block: Executes if no exception occurs in the try block.
#finally Block: Executes regardless of whether an exception occurred or not, often used for cleanup.

In [22]:
try:
    num = int(input("Enter a number: "))
    print(f"The number is {num}")
except ValueError:
    print("Invalid input! Please enter a valid number.")

Enter a number:  


Invalid input! Please enter a valid number.


In [29]:
try:
    file = open("assessment.txt", "r")
    content = file.read()
    print(content)
except FileNotFoundError:
    print("File not found!")
else:
    print("File read successfully.")
finally:
    if 'file' in locals() and not file.closed:
        file.close()
        print("File closed.")


File read successfully.
File closed.


In [27]:
try:
    a = int(input("numerator: "))
    b = int(input("denominator: "))
    result = a / b
    print(f"Result: {result}")
except ValueError:
    print("Invalid input")
except ZeroDivisionError:
    print("Division by zero error.")

numerator:  9
denominator:  0


Division by zero error.


In [ ]:
#functions
#functions are reusable blocks of code designed to perform a specific task

In [4]:
#define a function using the def keyword
def wish():
    print("Good morning!")

In [5]:
#calling a function
wish()

Good morning!


In [6]:
#Functions with Parameters
def profile(name):
    print(f"My name is , {name}!")

In [9]:
profile('kanmani')

My name is , kanmani!


In [11]:
#Functions with Return Values
def sub(a,b):
    return a-b

In [16]:
result = sub(9,3)
print(f"answer is {result}")

answer is 6


In [18]:
#default parameters
def profile(name=""):
    print(f'Welcome {name}')

In [21]:
name= "kanmani"
profile(name)

Welcome kanmani


In [2]:
#function with two arguments
def student(mark , grade):
    print(f"My mark is {mark} and my grade is {grade}")


In [3]:
student(900,'A')

My mark is 900 and my grade is A


In [3]:
# Variable Length Arguments
def add(*args):
    return add(args)

In [ ]:
add(4,6,7,9,2,7)

In [18]:
cube = lambda x: x**3
print(cube(4))

64


In [19]:
#factorial
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

In [20]:
print(factorial(7))

5040


In [ ]:
python built in functions

In [ ]:
#abs(x): Returns the absolute value of a number.
#round(x, n): Rounds a number to n decimal places.
#pow(x, y): Returns $$x^y$$ (x raised to the power of y).
#sum(iterable): Returns the sum of all elements in an iterable.

In [ ]:
#int(x): Converts x to an integer.
#float(x): Converts x to a floating-point number.
#str(x): Converts x to a string.
#list(iterable): Converts an iterable to a list.

In [ ]:
#print(*objects): Prints objects to the console.
#input(prompt): Reads input from the user as a string.

In [ ]:
#len(obj): Returns the length of an object (e.g., list, string, dictionary).
#max(iterable): Returns the largest item in an iterable.
#min(iterable): Returns the smallest item in an iterable.
#sorted(iterable): Returns a sorted list from the iterable.

In [ ]:
#type(obj): Returns the type of an object.
#id(obj): Returns the memory address of an object.
#help(obj): Displays the documentation for an object.
#dir(obj): Lists the attributes and methods of an object.

In [ ]:
1#isinstance(), issubclass()
#complex(), bool(), tuple(), set(), dict()
#ord(), chr(), hex(), bin(), oct()

In [ ]:
#range(): Generates a sequence of numbers.
#enumerate(): Adds an index to an iterable.
#zip(): Combines multiple iterables.
#map(), filter(), sorted(), reversed()

In [ ]:
#any(), all(): Check conditions in iterables.
#eval(): Evaluates a string as Python code.
#exec(): Executes Python code dynamically.
#callable(): Checks if an object is callable.
#hash(): Returns the hash value of an object.

In [ ]:
#numpy pandas
# numerical computing 
#support for large, multi-dimensional arrays and matrices

In [1]:
import numpy as np

In [2]:
#create array
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
#tells the dimension of the array
arr.shape 

(3,)

In [4]:
#finds the number of dimensions of the array 
arr.ndim

1

In [5]:
#tells the data type
arr.dtype

dtype('int64')

In [6]:
a3 = np.array([
 [[1, 2], [3, 4]],
 [[5, 6], [7, 8]]
])

In [8]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
#create a new of given shape filled with 0's
z=np.zeros((2,3))

In [10]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#create array filled with 1's
r=np.ones((2,3))

In [12]:
r

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#create an array with evenly spaced values within a specified range
d=np.arange(0,10,2) 

In [14]:
d

array([0, 2, 4, 6, 8])

In [15]:
#used to generate evenly spaced numbers over a specified range
f=np.linspace(5,50,5)

In [16]:
f

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

In [19]:
#creates a 2D array with ones on the main diagonal and zeros elsewhere,
#identity matrix
i=np.eye(3)

In [20]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#element wise operation

In [23]:
s=np.array([1,2,3,4])
s

array([1, 2, 3, 4])

In [24]:
r=np.array([6,7,8,9])
r

array([6, 7, 8, 9])

In [25]:
s+r

array([ 7,  9, 11, 13])

In [26]:
s*r

array([ 6, 14, 24, 36])

In [27]:
s**2

array([ 1,  4,  9, 16])

In [ ]:
#np.zeros((2, 3)) # 2x3 array of zeros
#np.ones((2, 2)) # 2x2 array of ones
#np.eye(3) # 3x3 identity matrix
#np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
#np.linspace(0, 1, 5) # 5 values between 0 and 1

In [46]:
#matrix multiplication
y=np.dot(s,r)

In [47]:
y

np.int64(80)

In [30]:
k=np.array([5,6,7],dtype=float)

In [31]:
k

array([5., 6., 7.])

In [33]:
#given mean value
w=np.mean(s)

In [34]:
w

np.float64(2.5)

In [35]:
#gives median value
f=np.median(s) #no mode

In [36]:
f

np.float64(2.5)

In [37]:
#gives standard deviation value
u=np.std(s)

In [38]:
u

np.float64(1.118033988749895)

In [39]:
#gives the sine value in array
#also will work with all trignometric operations like cos ,tan etc
q=np.sin(s)

In [40]:
q

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
# gives the sorted array values without duplication
np.unique(s)

array([1, 2, 3, 4])

In [42]:
s

array([1, 2, 3, 4])

In [43]:
#arrange the array values in ascending
np.sort(s)

array([1, 2, 3, 4])

In [44]:
s

array([1, 2, 3, 4])

In [45]:
#combines two array
np.concatenate([s,r])

array([1, 2, 3, 4, 6, 7, 8, 9])